/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe.swing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import ticatactoe.managers.GameManager;
import tictactoe.models.ButtonWrapper;

/**
 *
 * @author abhi
 */
public class GameBoardScreen extends javax.swing.JFrame implements ActionListener{
    ArrayList<ButtonWrapper> mBoardButtons = new ArrayList<>();
    

    /**
     * Creates new form GameBoardScreen
     */
    public GameBoardScreen() {
        initComponents();
        setLocationRelativeTo(null);
        
        initButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        mPlayerChanceLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jButton10.setLabel("Restart Game");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        mPlayerChanceLabel.setText("jLabel1");
        mPlayerChanceLabel.setAlignmentX(0.5F);
        mPlayerChanceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(mPlayerChanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(mPlayerChanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        mPlayerChanceLabel.getAccessibleContext().setAccessibleName("mPlayerChanceLabel");

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jButton1.setText("jButton1");
        jButton1.setActionCommand("0");
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setActionCommand("1");
        jPanel1.add(jButton2);

        jButton3.setText("jButton3");
        jButton3.setActionCommand("2");
        jPanel1.add(jButton3);

        jButton4.setText("jButton4");
        jButton4.setActionCommand("3");
        jPanel1.add(jButton4);

        jButton5.setText("jButton5");
        jButton5.setActionCommand("4");
        jPanel1.add(jButton5);

        jButton6.setText("jButton6");
        jButton6.setActionCommand("5");
        jPanel1.add(jButton6);

        jButton7.setText("jButton7");
        jButton7.setActionCommand("6");
        jPanel1.add(jButton7);

        jButton8.setText("jButton8");
        jButton8.setActionCommand("7");
        jPanel1.add(jButton8);

        jButton9.setText("jButton9");
        jButton9.setActionCommand("8");
        jPanel1.add(jButton9);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        reset();
        GameManager.getInstance().restartGame();
    }//GEN-LAST:event_jButton10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mPlayerChanceLabel;
    // End of variables declaration//GEN-END:variables

    public void reset(){
        updateBoardButtons();
        updateChance(GameManager.getInstance().getCurrentPlayer(),GameManager.getInstance().getPlayer1Name(),GameManager.getInstance().getPlayer2Name());
    }
    public void updateChance(int player, String player1Name, String player2Name) throws IllegalArgumentException{
        switch (player) {
            case 0:
                mPlayerChanceLabel.setText("Current Chance: "+player1Name);
                break;
            case 1:
                mPlayerChanceLabel.setText("Current Chance: "+player2Name);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initButtons(){
        mBoardButtons.add(new ButtonWrapper(jButton1));
        mBoardButtons.add(new ButtonWrapper(jButton2));
        mBoardButtons.add(new ButtonWrapper(jButton3));
        mBoardButtons.add(new ButtonWrapper(jButton4));
        mBoardButtons.add(new ButtonWrapper(jButton5));
        mBoardButtons.add(new ButtonWrapper(jButton6));
        mBoardButtons.add(new ButtonWrapper(jButton7));
        mBoardButtons.add(new ButtonWrapper(jButton8));
        mBoardButtons.add(new ButtonWrapper(jButton9));
        
        int i = 0;
        for(ButtonWrapper wrapper: mBoardButtons){
            wrapper.getButton().addActionListener(this); 
            wrapper.setPosition(i);
            i++;
        }
        
        updateBoardButtons();
    }
    
    public void updateBoardButtons(){
        for(ButtonWrapper wrapper: mBoardButtons){
            wrapper.getButton().setEnabled(true);
            wrapper.setText("");
            wrapper.getButton().setBackground(null);
            wrapper.getButton().setOpaque(false);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton button = (JButton)e.getSource();
        String actionCommand = button.getActionCommand();
        int position = Integer.parseInt(actionCommand);
        System.out.println("Button No. "+actionCommand);
        GameManager.getInstance().playChance(mBoardButtons, position);
        updateChance(GameManager.getInstance().getCurrentPlayer(),GameManager.getInstance().getPlayer1Name(),GameManager.getInstance().getPlayer2Name());
    }
    public ArrayList<ButtonWrapper> getBoardButtons(){
        return mBoardButtons;
    }
}
